language: c
env:
  global:
    # list of package to clone via git
    #- GAP_PKGS_TO_CLONE="SOME_PACKAGE"
    # list of package to compile; io and profiling are always needed for coverage reports
    #- GAP_PKGS_TO_BUILD="io profiling SOME_OTHER_PACKAGE"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: GAPBRANCH=master
    - env: GAPBRANCH=stable-4.10
    - env: GAPBRANCH=stable-4.9

branches:
  only:
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
